#version: "3.9"

services:
  backend:
    image: practica4backend:1.0.0
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: backend-django2
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT}:8000" # Mapea el puerto 8000 del contenedor al 8000 de tu máquina
    environment:
      - DEBUG=1
    restart: unless-stopped

  # frontend:
  #   image: practica4:1.0.1
  #   build:
  #     context: ./../frontend
  #     dockerfile: Dockerfile
  #   container_name: frontend-react2
  #   env_file:
  #     - .env
  #   environment:
  #     REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL}
  #   ports:
  #     - "${FRONTEND_PORT}:3000" # Mapea el puerto 3000 del contenedor al 3000 de tu máquina
  #   # depends_on:
  #   #   - backend # Se asegura que el backend esté levantado primero
  #   restart: unless-stopped
