[supervisord]
nodaemon=true

[program:gunicorn]
command=gunicorn --workers=3 --bind=0.0.0.0:8000 api.wsgi:application
directory=/app
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stdout_logfile=/dev/stdout

[program:celery]
command=celery -A api worker --loglevel=info
directory=/app
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stdout_logfile=/dev/stdout
